<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfect Pitch Trainer</title>
    <style>
        body { font-family: sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #f0f0f0; }
        #status { margin-bottom: 20px; font-size: 1.2rem; font-weight: bold; }
        .button-container { display: flex; gap: 20px; }
        .chord-btn { width: 120px; height: 120px; border-radius: 15px; border: none; cursor: pointer; transition: transform 0.1s; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        .chord-btn:active { transform: scale(0.95); }
        #play-btn { padding: 15px 30px; font-size: 1.2rem; margin-bottom: 40px; cursor: pointer; background: #333; color: white; border-radius: 8px; border: none; }
    </style>
</head>
<body>

    <div id="status">Listen to the chord...</div>
    <button id="play-btn">Play Random Chord</button>

    <div class="button-container" id="game-ui">
        <!-- Buttons generated by JavaScript -->
    </div>

<script>
    // --- 1. CONFIGURATION: UPDATED COLORS AND CHORDS ---
    const chordConfig = [
        { 
            name: "C Major (C E G)", 
            notes: [261.63, 329.63, 392.00], 
            color: "#FF0000" // Red 
        },
        { 
            name: "F Major (C F A)", 
            notes: [261.63, 349.23, 440.00], 
            color: "#FFC0CB" // Pink
        }
    ];

    let currentChordIndex = null;
    const audioCtx = new (window.AudioContext || window.webkitAudioContext)();

    // --- 2. AUDIO ENGINE ---
    function playTriad(frequencies) {
        frequencies.forEach(freq => {
            const osc = audioCtx.createOscillator();
            const gain = audioCtx.createGain();
            osc.type = 'triangle'; 
            osc.frequency.setValueAtTime(freq, audioCtx.currentTime);
            
            gain.gain.setValueAtTime(0.1, audioCtx.currentTime);
            gain.gain.exponentialRampToValueAtTime(0.0001, audioCtx.currentTime + 1.5);

            osc.connect(gain);
            gain.connect(audioCtx.destination);
            osc.start();
            osc.stop(audioCtx.currentTime + 1.5);
        });
    }

    // --- 3. GAME LOGIC ---
    const uiContainer = document.getElementById('game-ui');
    const statusText = document.getElementById('status');

    // Create buttons based on config
    chordConfig.forEach((chord, index) => {
        const btn = document.createElement('button');
        btn.className = 'chord-btn';
        btn.style.backgroundColor = chord.color;
        btn.title = chord.name; // Shows chord name on hover
        btn.onclick = () => checkAnswer(index);
        uiContainer.appendChild(btn);
    });

    document.getElementById('play-btn').onclick = () => {
        // Resume AudioContext for browsers that block auto-play
        if (audioCtx.state === 'suspended') {
            audioCtx.resume();
        }
        currentChordIndex = Math.floor(Math.random() * chordConfig.length);
        playTriad(chordConfig[currentChordIndex].notes);
        statusText.innerText = "Which color was that?";
        statusText.style.color = "black";
    };

    function checkAnswer(index) {
        if (currentChordIndex === null) return;
        if (index === currentChordIndex) {
            statusText.innerText = "Correct! Well done.";
            statusText.style.color = "green";
        } else {
            statusText.innerText = "Try again!";
            statusText.style.color = "red";
        }
    }
</script>
</body>
</html>
